apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-product-service-app
  labels:
    app: catalog-product-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-product-service-app
  template:
    metadata:
      labels:
        app: catalog-product-service-app
    spec:
      containers:
        - name: catalog-product-service-app
          image: qkanban/microservice-docker-catalog-product-service:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 9080

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-product-service-svc
spec:
  type: ClusterIP
  selector:
    app: catalog-product-service-app
  ports:
    - targetPort: 9080
      port: 80
