apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-app
  labels:
    app: vault-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-app
  template:
    metadata:
      labels:
        app: vault-app
    spec:
      containers:
        - name: vault-app
          image: jboss/vault:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8200

---
apiVersion: v1
kind: Service
metadata:
  name: vault-svc
spec:
  type: ClusterIP
  selector:
    app: vault-app
  ports:
    - targetPort: 8200
      port: 80
