apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-app
  labels:
    app: zipkin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-app
  template:
    metadata:
      labels:
        app: zipkin-app
    spec:
      containers:
        - name: zipkin-app
          image: jboss/zipkin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9411

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-svc
spec:
  type: ClusterIP
  selector:
    app: zipkin-app
  ports:
    - targetPort: 9411
      port: 80
