server:
  port: 9296

spring:
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: never
  profiles:
    active: git, vault
  application:
     name:  CONFIG-SERVER
  cloud:
     config:
       server:
          git:
            uri: https://github.com/jbfm21/cloud-config-server
            default-label: main
            clone-on-start: true
          vault:
            host: 127.0.0.1
            port: 8200
            scheme: http
            authentication: TOKEN
            token: s.7qcnq2z7xMGrjwYQg62SiYIm
            kv-version: 2
