server: 
  port: 8761
  
spring:
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: never
  profiles:
    active: dev
  application: 
     name: SERVICE-REGISTRY

#Local configuration 
eureka:  client:
    #COmo é o servidor não se registra    register-with-eureka: false
    fetch-registry: false

#K8S configuration
#eureka:
#  instance:
#    hostname: "${HOSTNAME}.eureka"
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    serviceUrl:
#      defaultZone: ${EUREKA_SERVER_ADDRESS}  